### ISSUE TITLE
Fix border in search icon

### ISSUE THREAD

**Issue by wanderdust** [wanderdust/search-courses#14]
**Problem**:
The border of the magnifying glass is round and the search box doesn't look too nice because of it.

**Solution**:
The border of the magnifying glass shouldn't be round. Make it as if the search bar and the icon were one. box

![Screenshot (5)](https://user-images.githubusercontent.com/26457618/67334489-2332d700-f51a-11e9-8846-ad4ae99d67b8.png)

**Comment by reegoram** [comment]
Has anyone fixed this? I couldn't replicate it, I've just downloaded the recent code but the icon doesn't look rounded. This is related to the search bar in the header, right?

**Comment by wanderdust** [comment]
Hey @reegoram, that's odd. It should be on the most recent version of master. I will try and have a look tomorrow and get back to you.

**Comment by wanderdust** [comment]
Hey @reegoram, if you want to see the most updated version on the app on production mode (that is using `npm start` and running the server on port 3000) make sure you run `npm run build:prod` to update the app to the most recent version. I think this might have been the problem, as you were seeing an old version of the app.

If you run the app in development mode (that is using `npm run dev-server` and running the server on port 8080) you won't need to do anything to see the app in the most recent version. Also in development mode the server will update automatically with any changes.

I've updated the readme file to try and make this a bit more clear. Let me know if you still have any problems.

**Comment by reegoram** [comment]
Ok, I've got it. I haven't ```npm run build:prod```. 
Thanks, I'm opening a pull request with the fix soon.
